logging:
  pattern:
    console: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  level:
    dev.bank: DEBUG

spring:
  # DB 연결
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    show-sql: true
    hibernate.hbm2ddl.auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

#    hibernate:
#      ddl-auto: create